# Publishes the Storybook instance to Chromatic.

image: node:10.15.0
pipelines:
  default:
    - step:
        name: 'Publish to Chromatic'
        caches:
          - node
        script:
          - cd app
          - npm install
          - npm run chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --build-script-name=storybook-build --output-dir=storybook-static
