# Publishes the Storybook instance to Chromatic.

image: node:10.15.0
pipelines:
  default:
    - step:
        name: 'Publish to Chromatic'
        cache:
          - node
        script:
          - cd app
          - yarn install
          - yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --build-script-name=storybook-build --output-dir=storybook-static
