# Publishes the Storybook instance to Chromatic.

image: node:10.15.0
pipelines:
  default:
    - step:
        name: 'Publish to Chromatic'
        caches:
          - node
        script:
          - echo "NACELLE_SPACE=cosmic-shuttle-eZTT89JiAp$'\nNACELLE_TOKEN=a8ee3969-ebe0-407c-a476-609255954b5c" > ./www/.env
          - cd app
          - npm install
          - npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --build-script-name=storybook-build --output-dir=storybook-static
