query customerOrders($customerAccessToken: String!) {
  customer(customerAccessToken: $customerAccessToken) {
    orders(first: 100) {
      edges {
        node {
          id
          orderNumber
          fulfillmentStatus
          financialStatus
          processedAt
          shippingAddress {
            formatted
          }
          currentSubtotalPrice {
            amount
          }
          currentTotalPrice {
            amount
          }
          currentTotalTax {
            amount
          }
          totalShippingPriceV2 {
            amount
          }
        }
      }
    }
  }
}
