query customerOrders($customerAccessToken: String!) {
  customer(customerAccessToken: $customerAccessToken) {
    orders(first: 100) {
      edges {
        node {
          orderNumber
          fulfillmentStatus
          processedAt
          totalPriceV2 {
            amount
          }
        }
      }
    }
  }
}
